# Generated by Django 2.1.5 on 2019-02-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190210_1806'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job',
            new_name='jobs',
        ),
    ]
