# Generated by Django 3.0.8 on 2020-07-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190216_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='summary',
            new_name='movieDescription',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='image',
            new_name='moviePoster',
        ),
    ]
