# Generated by Django 2.1.5 on 2019-06-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190625_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Publication_Date',
            new_name='pub_date',
        ),
    ]
