# Generated by Django 3.0.8 on 2020-07-24 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190625_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='pub_date',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='body',
            new_name='movieDescription',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='movieName',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='moviePoster',
        ),
    ]
